/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ams.lacdb.mods;

import ams.index;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;
import java.util.Iterator;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.*;


import java.io.*;
import java.sql.*;
import java.util.Iterator;
import javax.swing.*;

/**
 *
 * @author Reharsh
 */import java.io.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
 
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.*;
public class Excel extends javax.swing.JFrame {

    /**
     * Creates new form Excel
     */
    public Excel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("Enter path only Excel Files");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(598, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(423, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         boolean stat = false;
        try {
              INSERT();
        } catch (Exception ex) {
            Logger.getLogger(Excel.class.getName()).log(Level.SEVERE, null, ex);
        }
       /* if(stat==true)
        {
             JOptionPane.showMessageDialog(null, "Sucess", "Ecxllent", 1);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Failed", "Ecxllent", 1);
        }*/
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     *
     * @return
     * @throws java.lang.Exception
     */
    public void INSERT() 
    {
            
        String s1="",s2="";
         JFileChooser fc=new JFileChooser();    
    int i=fc.showOpenDialog(this);    
    if(i==JFileChooser.APPROVE_OPTION){    
       File f=fc.getSelectedFile();    
        String filepath=f.getAbsolutePath();    
   
       jTextField1.setText(filepath);    
          System.out.println(filepath);
    } 
        String jdbcURL = "jdbc:mysql://localhost:3306/assessment";
        String username = "root";
        String password = "";
 
        //String excelFilePath = "Students.xlsx";
 
        int batchSize = 20;
 
        Connection connection = null;
 
        try {
            //long start = System.currentTimeMillis();
             
 
            PreparedStatement statement;
             InputStream inputStream = new FileInputStream("C:/Users/Reharsh/Desktop/aa.xlsx");
                    Workbook workbook = new XSSFWorkbook(inputStream) ;
                     
                Sheet firstSheet = workbook.getSheetAt(0);
                DataFormatter formatter = new DataFormatter();
                Iterator<Row> rowIterator = firstSheet.iterator();
                connection = DriverManager.getConnection(jdbcURL, username, password);
                connection.setAutoCommit(false);
                String sql = "insert into final_root (Programme_code,Course_Code,Course_Name,year) VALUES ( ?, ?, ?, ?)";
                statement = connection.prepareStatement(sql);
                
                int count = 0;
                rowIterator.next(); // skip the header row
                while (rowIterator.hasNext()) {
                    Row nextRow = rowIterator.next();
                    Iterator<Cell> cellIterator = nextRow.cellIterator();
                    
                    while (cellIterator.hasNext()) {
                    
                        Cell nextCell = cellIterator.next();
                        
                        int columnIndex = nextCell.getColumnIndex();
                        int rowIndex =nextRow.getRowNum();
                        switch (columnIndex) {
                            
                            case 0:
                                String pc = nextCell.getStringCellValue();
                                statement.setString(1, pc);
                                break;
                              
                            case 1:
                                String cc =  nextCell.getStringCellValue();
                                statement.setString(2,cc);
                           
                                case 2:
                                String cn =  nextCell.getStringCellValue();
                                statement.setString(3,cn);
                                case 3:
                                String y = formatter.formatCellValue(firstSheet.getRow(rowIndex).getCell(columnIndex));
                                statement.setString(4, y);
                                /*case 4:
                                String tn = Double.toString(nextCell.getNumericCellValue());
                                statement.setString(5, tn);*/
                                
                        }
                        
                    }
 
                    statement.addBatch();
                    
                    if (count % batchSize == 0) {
                        statement.executeBatch();
                    }
                    
                }
            
             
            // execute the remaining queries
            statement.executeBatch();
  
            connection.commit();
            connection.close();
              JOptionPane.showMessageDialog(null, "Sucess", "Ecxllent", 1);
            //long end = System.currentTimeMillis();
           //System.out.printf("Import done in %d ms\n", (end - start));
             
        }catch(Exception e){
            System.out.print(e.getMessage());
            e.printStackTrace();
        }
        
    }
    
    
    
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        java.awt.EventQueue.invokeLater(() -> {
            new Excel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
